https://pytorch.org/docs/stable/index.html

https://habr.com/ru/post/334380/

https://pythonist-ru.turbopages.org/pythonist.ru/s/glubokoe-obuchenie-i-nejronnye-seti-s-python-i-pytorch-dannye-chast-ii/

https://neurohive.io/ru/tutorial/glubokoe-obuchenie-s-pytorch/

# 0. Введение в PyTorch. Ознакомление с фреймворком

## Установка фреймворка

In [3]:
# напрямую
pip install torch

In [ ]:
# в анаконде
conda install pytorch torchvision cpuonly -c pytorch

## Тензоры

In [1]:
import torch

In [37]:
torch.Tensor(2, 3) # Тензор заполненный нулями

tensor([[5.8855e-44, 1.4994e-43, 1.6675e-43],
        [1.4013e-43, 1.6115e-43, 5.7453e-44]])

In [59]:
x = torch.Tensor([1,2,3,4]) # Tensor = FloatTensor
y = torch.IntTensor([1,2,3,4])

In [60]:
x * y

tensor([ 1.,  4.,  9., 16.])

In [26]:
(x - y).type_as(y)

tensor([0, 0, 0, 0], dtype=torch.int32)

In [33]:
z = torch.Tensor([[1, 2], [3, 4], [5,6]])
z

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [34]:
z.shape

torch.Size([3, 2])

In [35]:
z.type()

'torch.FloatTensor'

In [36]:
z.dim()

2

In [37]:
z.size()

torch.Size([3, 2])

In [32]:
z.data_ptr() # место в памяти, где находятся данные

1994584131520

In [39]:
x.exp() # immutable foo
x

tensor([1., 2., 3., 4.])

In [40]:
x.exp_() # mutable foo or inplace
x

tensor([ 2.7183,  7.3891, 20.0855, 54.5981])

In [41]:
x.fill_(3)

tensor([3., 3., 3., 3.])

In [45]:
u = torch.eye(3, 5)
u

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]])

In [46]:
u.t_()

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [47]:
u.shape

torch.Size([5, 3])

In [50]:
z.sum(), z.sum(dim=1)

(tensor(21.), tensor([ 3.,  7., 11.]))

In [51]:
z.max(), z.max(dim=1)

(tensor(6.),
 torch.return_types.max(
 values=tensor([2., 4., 6.]),
 indices=tensor([1, 1, 1])))

In [53]:
z.mean(), z.mean(dim=1)

(tensor(3.5000), tensor([1.5000, 3.5000, 5.5000]))

In [52]:
z.median(), z.median(dim=1)

(tensor(3.),
 torch.return_types.median(
 values=tensor([1., 3., 5.]),
 indices=tensor([0, 0, 0])))

In [54]:
import numpy as np

In [9]:
a = np.random.rand(3, 3)
a

array([[0.60337625, 0.14222343, 0.30661121],
       [0.41677107, 0.73177124, 0.40704845],
       [0.96258588, 0.92717595, 0.01798961]])

In [10]:
b = torch.from_numpy(a)
b

tensor([[0.6034, 0.1422, 0.3066],
        [0.4168, 0.7318, 0.4070],
        [0.9626, 0.9272, 0.0180]], dtype=torch.float64)

In [69]:
x = torch.Tensor(4, 4).uniform_()
x.is_cuda

False

In [8]:
device = "cuda:0" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [11]:
b.to(device)

tensor([[0.6034, 0.1422, 0.3066],
        [0.4168, 0.7318, 0.4070],
        [0.9626, 0.9272, 0.0180]], dtype=torch.float64)

In [12]:
b.get_device()

-1

In [78]:
x.cpu()

tensor([[0.5741, 0.5989, 0.9856, 0.5657],
        [0.9239, 0.5123, 0.5799, 0.0561],
        [0.3518, 0.3603, 0.7000, 0.5047],
        [0.2708, 0.0600, 0.1195, 0.3456]])

In [83]:
b.data

tensor([[0.4261, 0.8968, 0.8472],
        [0.2044, 0.2506, 0.6265],
        [0.6059, 0.5177, 0.0538]], dtype=torch.float64)

## Автоматическое дифференцирование

In [2]:
from torch.autograd import Variable

In [26]:
x = torch.FloatTensor(3, 1).uniform_()
w = torch.FloatTensor(3, 3).uniform_() 
b = torch.FloatTensor(3, 1).uniform_()

In [27]:
x = Variable(x, requires_grad=True) # создание переменной из простого тензора, которой необходим градиаент
w = Variable(w)
b = Variable(b)

In [28]:
x, w, b

(tensor([[0.5179],
         [0.2670],
         [0.8274]], requires_grad=True),
 tensor([[0.9279, 0.6172, 0.3261],
         [0.4162, 0.8558, 0.3307],
         [0.9439, 0.2913, 0.8827]]),
 tensor([[0.4479],
         [0.7666],
         [0.7892]]))

In [29]:
y = w @ x + b

In [30]:
y, x, w, b

(tensor([[1.3631],
         [1.4842],
         [2.0861]], grad_fn=<AddBackward0>),
 tensor([[0.5179],
         [0.2670],
         [0.8274]], requires_grad=True),
 tensor([[0.9279, 0.6172, 0.3261],
         [0.4162, 0.8558, 0.3307],
         [0.9439, 0.2913, 0.8827]]),
 tensor([[0.4479],
         [0.7666],
         [0.7892]]))

In [31]:
loss = y.sum()
loss

tensor(4.9334, grad_fn=<SumBackward0>)

In [32]:
loss.backward()

In [40]:
x.data, x.grad

(tensor([[0.5179],
         [0.2670],
         [0.8274]]),
 tensor([[2.2880],
         [1.7644],
         [1.5395]]))

## Нейронка

In [34]:
from torch import nn

In [ ]:
class Net(nn.Module):
    
    def __init__(self):
        super().__init__()
        self.linear = nn.Sequential(
           nn.Linear(28 * 28, 256),
           nn.ReLU(),
           nn.Linear(256, 256),
           nn.ReLU(),
           nn.Linear(256, 10)
        ) # задаем архитектуру нейронки
        
    def forward(self, x):
        return self.linear(x)

In [35]:
from torch.utils.data import Dataset, DataLoader